server:
  port: 8090
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, fhc
      #用前缀匹配路由器请求转发
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**

#调整日志级别
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace



dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
